/**
 * Icon set — Phosphor (design-brief §3, owner 2026-07-08: richer than plain line
 * icons; weights available per-use: regular · bold · fill · duotone via the `weight`
 * prop). Re-exported through @beecompete/ui so app code never imports an icon library
 * (or inlines SVGs) directly. The `/dist/ssr` entry is context-free, so these work in
 * both server and client components.
 *
 * Curated: add icons here as features need them, keeping usage searchable.
 * Some names are aliased to keep call sites descriptive and stable.
 */
export {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowSquareOut as ExternalLink,
  ArrowCounterClockwise as Restore,
  Article,
  Bank,
  Bell,
  BookOpen,
  BookmarkSimple as Bookmark,
  Brain,
  Briefcase,
  Buildings,
  CalendarBlank as Calendar,
  CalendarPlus,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  ChatCircleText as MessageCircle,
  Check,
  CheckCircle,
  CircleNotch as Spinner,
  Clock,
  Code,
  Copy,
  CurrencyDollar as DollarSign,
  Envelope as Mail,
  FacebookLogo as Facebook,
  FilePdf,
  Flag,
  Flask,
  FloppyDisk as Save,
  FunnelSimple as Filter,
  Globe,
  GraduationCap,
  Heart,
  ImageSquare,
  Info,
  Link as LinkIcon,
  LinkedinLogo as Linkedin,
  ListBullets as ListIcon,
  MagnifyingGlass as Search,
  MapPin,
  MathOperations,
  Medal,
  Microphone,
  Moon,
  MusicNotes,
  Palette,
  PencilSimple as Pencil,
  PenNib,
  PlayCircle,
  Plus,
  Robot,
  Question as CircleHelp,
  SealCheck as VerifiedSeal,
  ShareNetwork as Share,
  SignOut,
  Sparkle as Sparkles,
  SquaresFour as Dashboard,
  Star,
  Sun,
  Tag,
  Ticket,
  TrashSimple as Trash,
  Tray,
  Trophy,
  User,
  UsersThree as Users,
  Warning,
  WarningCircle as CircleAlert,
  WhatsappLogo as Whatsapp,
  X,
  XLogo,
} from '@phosphor-icons/react/dist/ssr';
