/**
 * Icon set — Lucide line icons (design-brief §3), re-exported through @beecompete/ui
 * so app code never imports an icon library (or inlines SVGs) directly. Curated:
 * add icons here as features need them, keeping usage searchable in one place.
 */
export {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  Bookmark,
  Calendar,
  CalendarPlus,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  Clock,
  DollarSign,
  ExternalLink,
  Filter,
  Flag,
  Globe,
  GraduationCap,
  Heart,
  Info,
  Link as LinkIcon,
  Loader2,
  MapPin,
  Medal,
  Menu,
  Moon,
  Search,
  Share2,
  Sparkles,
  Sun,
  Trophy,
  Users,
  X,
} from 'lucide-react';
